version: "2"
services:
  server:
    build: .
    container_name: "nodejs"
    ports:
    - "8081:8080"
    - "3000:3000"
    links:
    - mongodb
    depends_on:
    - mongodb
  mongodb:
      image: mongo
      container_name: "mongodb"

      volumes:
        - ./mongo/db:/data/db
      ports:
      - "27017:27017"
